// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyPhatTu;

#nullable disable

namespace QuanLyPhatTu.Migrations
{
    [DbContext(typeof(ApDbContext))]
    [Migration("20230615043513_data")]
    partial class data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyPhatTu.Entities.Chuas", b =>
                {
                    b.Property<int>("ChuaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChuaId"));

                    b.Property<DateTime>("CapNhat")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayThanhLap")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenChua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TruTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChuaId");

                    b.ToTable("Chuas");
                });

            modelBuilder.Entity("QuanLyPhatTu.Entities.DaoTrangs", b =>
                {
                    b.Property<int>("DaoTrangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DaoTrangId"));

                    b.Property<bool>("DaKetThuc")
                        .HasColumnType("bit");

                    b.Property<int>("NguoiChuTriId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiToChuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoThanhVienThamGia")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianToChuc")
                        .HasColumnType("datetime2");

                    b.HasKey("DaoTrangId");

                    b.HasIndex("NguoiChuTriId");

                    b.ToTable("DaoTrangs");
                });

            modelBuilder.Entity("QuanLyPhatTu.Entities.DonDangKys", b =>
                {
                    b.Property<int>("DonDangKyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonDangKyId"));

                    b.Property<DateTime>("NgayGuiDon")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySuLy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiSuLyId")
                        .HasColumnType("int");

                    b.Property<int>("PhatTuId")
                        .HasColumnType("int");

                    b.Property<int>("TrangThaiDon")
                        .HasColumnType("int");

                    b.HasKey("DonDangKyId");

                    b.HasIndex("PhatTuId");

                    b.ToTable("DonDangKys");
                });

            modelBuilder.Entity("QuanLyPhatTu.Entities.KieuThanhViens", b =>
                {
                    b.Property<int>("KieuThanhVienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KieuThanhVienId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KieuThanhVienId");

                    b.ToTable("KieuThanhViens");
                });

            modelBuilder.Entity("QuanLyPhatTu.Entities.PhatTuDaoTrangs", b =>
                {
                    b.Property<int>("PhatTuDaoTrangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhatTuDaoTrangId"));

                    b.Property<bool>("DaThamGia")
                        .HasColumnType("bit");

                    b.Property<int>("DaoTrangId")
                        .HasColumnType("int");

                    b.Property<string>("LyDoKhongThamGia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PhatTuId")
                        .HasColumnType("int");

                    b.HasKey("PhatTuDaoTrangId");

                    b.HasIndex("DaoTrangId");

                    b.HasIndex("PhatTuId");

                    b.ToTable("PhatTuDaoTrangs");
                });

            modelBuilder.Entity("QuanLyPhatTu.Entities.PhatTus", b =>
                {
                    b.Property<int>("PhatTuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhatTuId"));

                    b.Property<string>("AnhChup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ChuaId")
                        .HasColumnType("int");

                    b.Property<int?>("ChuasChuaId")
                        .HasColumnType("int");

                    b.Property<bool>("DaHoanTuc")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KieuThanhVienId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHoanTuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXuatGia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhapDanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhatTuId");

                    b.HasIndex("ChuasChuaId");

                    b.HasIndex("KieuThanhVienId");

                    b.ToTable("PhatTus");
                });

            modelBuilder.Entity("QuanLyPhatTu.Entities.DaoTrangs", b =>
                {
                    b.HasOne("QuanLyPhatTu.Entities.PhatTus", "NguoiChuTri")
                        .WithMany("DaoTrangs")
                        .HasForeignKey("NguoiChuTriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiChuTri");
                });

            modelBuilder.Entity("QuanLyPhatTu.Entities.DonDangKys", b =>
                {
                    b.HasOne("QuanLyPhatTu.Entities.PhatTus", "PhatTu")
                        .WithMany("DonDangKys")
                        .HasForeignKey("PhatTuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhatTu");
                });

            modelBuilder.Entity("QuanLyPhatTu.Entities.PhatTuDaoTrangs", b =>
                {
                    b.HasOne("QuanLyPhatTu.Entities.DaoTrangs", "DaoTrang")
                        .WithMany("PhatTuDaoTrangs")
                        .HasForeignKey("DaoTrangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyPhatTu.Entities.PhatTus", "PhatTu")
                        .WithMany("PhatTuDaoTrangs")
                        .HasForeignKey("PhatTuId");

                    b.Navigation("DaoTrang");

                    b.Navigation("PhatTu");
                });

            modelBuilder.Entity("QuanLyPhatTu.Entities.PhatTus", b =>
                {
                    b.HasOne("QuanLyPhatTu.Entities.Chuas", "Chuas")
                        .WithMany("PhatTus")
                        .HasForeignKey("ChuasChuaId");

                    b.HasOne("QuanLyPhatTu.Entities.KieuThanhViens", "KieuThanhVien")
                        .WithMany("PhatTus")
                        .HasForeignKey("KieuThanhVienId");

                    b.Navigation("Chuas");

                    b.Navigation("KieuThanhVien");
                });

            modelBuilder.Entity("QuanLyPhatTu.Entities.Chuas", b =>
                {
                    b.Navigation("PhatTus");
                });

            modelBuilder.Entity("QuanLyPhatTu.Entities.DaoTrangs", b =>
                {
                    b.Navigation("PhatTuDaoTrangs");
                });

            modelBuilder.Entity("QuanLyPhatTu.Entities.KieuThanhViens", b =>
                {
                    b.Navigation("PhatTus");
                });

            modelBuilder.Entity("QuanLyPhatTu.Entities.PhatTus", b =>
                {
                    b.Navigation("DaoTrangs");

                    b.Navigation("DonDangKys");

                    b.Navigation("PhatTuDaoTrangs");
                });
#pragma warning restore 612, 618
        }
    }
}
